import type { NextPage } from "next";
import Head from "next/head";
import { useQuery, gql } from "@apollo/client";
import styles from "../styles/Home.module.css";
import AdListComponent from "@/components/AdListComponent";

const GET_ALL_ADS = gql`
  query GetAllAds {
    getAllAds {
      content
      id
      title
    }
  }
`;

const Home: NextPage = () => {
  const { loading, error, data } = useQuery(GET_ALL_ADS);

  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error : {error.message}</p>;
  else {
    console.log(data);
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <AdListComponent />
        </main>
      </div>
    );
  }
};

export default Home;
